require('jslog.plugins.install')
require('jslog.plugins.fugitive')
require('jslog.plugins.telescope')
require('jslog.plugins.treesitter')
require('jslog.plugins.harpoon')
require('jslog.plugins.undotree')
require('jslog.plugins.lsp')
